name: corner_ribbon
description: "A customizable Flutter widget to add corner ribbons with text overlays to any widget."
version: 0.0.1
homepage: https://github.com/tajaouart/corner_ribbon
repository: https://github.com/tajaouart/corner_ribbon
issue_tracker: https://github.com/tajaouart/corner_ribbon/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
